---
title: "Machine Learning Motivation"
author: "JMG"
format: html
---

```{r}
#| warning: false
#| message: false
#| include: false

library(tidyverse)
library(tidytuesdayR)

theme_set(theme_minimal(base_size = 12))
```

## Board Game Data Motivating ML

First, let's get the data:

```{r}
#| echo: true
#| code-fold: true

# tuesdata <- tidytuesdayR::tt_load('2022-01-25')
```

Save the data sframes as csv files:

```{r}
#| echo: true
#| code-fold: true

#write_csv(tuesdata$details,"data/details.csv")
#write_csv(tuesdata$ratings,"data/ratings.csv")
```

Let's read in the data we downloaded:

```{r}
#| echo: true
#| code-fold: true
#| warning: false
#| message: false

details_df <- read_csv("data/details.csv")
ratings_df <- read_csv("data/ratings.csv")
```

```{r}
glimpse(details_df)
```


```{r}
glimpse(ratings_df)
```

```{r}
ratings_joined <-
  ratings_df %>%
  left_join(details_df, by = "id")
```

```{r}
glimpse(ratings_joined)
```

```{r}
ggplot(ratings_joined, aes(average)) +
  geom_histogram(alpha = 0.8)
```


```{r}

ratings_joined %>%
  filter(!is.na(minage)) %>%
  mutate(minage = cut_number(minage, 4)) %>%
  ggplot(aes(minage, average, fill = minage)) +
  geom_boxplot(alpha = 0.2, show.legend = FALSE)
```

```{r}
library(palmerpenguins)
```

```{r}
penguins %>%
  ggplot(aes(x=flipper_length_mm,y=body_mass_g,color=species)) + 
  geom_point()
```




